import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "zh" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  zh: {
    "nav.products": "产品",
    "nav.productsDesc": "创建 AI 驱动的研究项目",
    "nav.home": "首页",
    "nav.caseStudies": "案例研究",
    "nav.pricing": "定价",
    "nav.dashboard": "仪表盘",
    "nav.signIn": "登录",
    "nav.signOut": "退出",
    "nav.myStudies": "我的研究",
    
    // Home Page
    "home.hero.title": "AI 研究智能体",
    "home.hero.subtitle": "模拟消费者",
    "home.hero.description": "自动构建人物画像、进行访谈并分析模式，揭示人类选择背后的情感和认知因素。",
    "home.hero.cta": "开始您的研究",
    "home.stats.title": "大规模AI用户画像研究",
    "home.stats.subtitle": "构建真人智能体以理解",
    "home.stats.highlight": "人类决策",
    "home.stats.tag1": "AI人设",
    "home.stats.tag2": "专家访谈",
    "home.stats.tag3": "行为洞察",

    "home.workflow.sectionTitle": "主观世界建模实战",
    "home.workflow.mainTitle": "从问题到洞察，数分钟内完成",
    "home.workflow.step1.title": "AI人设生成",
    "home.workflow.step1.desc": "基于真实行为模式和人口统计洞察，生成多样化的AI人设。",
    "home.workflow.step2.title": "AI主导访谈",
    "home.workflow.step2.desc": "与AI人设进行自然对话，挖掘深层动机和关键决策驱动因素。",
    "home.workflow.step3.title": "行为分析",
    "home.workflow.step3.desc": "识别影响购买决策的情感触发点、认知偏见和文化因素。",
    "home.workflow.step4.title": "即时洞察",
    "home.workflow.step4.desc": "在数分钟内生成全面洞察，而非传统研究流程的数周时间。",

    "home.workflow.step1.button": "Generate AI Personas",
    "home.workflow.step2.button": "START INTERVIEW",
    "home.workflow.step3.button": "Analyze Behavior",
    "home.workflow.step4.button": "Download Report",

    "home.tech.sectionTitle": "CORE DIFFERENTIATOR",
    "home.tech.mainTitle": "超越人口统计学",
    "home.tech.description": "与传统调研数据或统计模型不同，我们的AI人设是复杂的行为模拟，在新情境中保持一致的个性特征和决策逻辑。",
    "home.tech.point1": "在不同情境下保持一致的个性特征和决策逻辑",
    "home.tech.point2": "模拟真实的人类认知偏见和情感反应",
    "home.tech.point3": "提供逼真、有深度的访谈回应，而不仅仅是数据聚合",
    
    "home.tech.ecosystemTitle": "AGENT ECOSYSTEM",
    "home.tech.ecosystemMainTitle": "智能体生态系统",
    "home.tech.card1.title": "AI模拟人设（社交媒体）",
    "home.tech.card1.desc": "基于社交媒体数据分析",
    "home.tech.card2.title": "AI样本数据生成人设（深度访谈/人群样本）",
    "home.tech.card2.desc": "基于深度访谈数据",
    "home.tech.card3.title": "AI孪生真人人设（私有）",
    "home.tech.card3.desc": "通过您自己的私有访谈数据构建",
    
    // Hero Section (legacy keys for compatibility)
    "hero.title": "AI 研究助手",
    "hero.subtitle": "模拟消费者行为",
    "hero.description": "自动构建人物画像、进行访谈并分析模式，揭示人类选择背后的情感和认知因素。",
    "hero.cta": "开始您的研究",
    "hero.trusted": "受领先组织信赖",
    
    // Features
    "features.title": "AI 驱动的消费者研究",
    "features.personaGen.title": "AI 人物画像生成",
    "features.personaGen.desc": "基于人口统计学和行为标准自动创建多样化的消费者画像",
    "features.interview.title": "模拟访谈",
    "features.interview.desc": "与 AI 人物画像进行自然对话，收集深度洞察和决策驱动因素",
    "features.analysis.title": "行为分析",
    "features.analysis.desc": "识别情感触发点、认知偏见和影响购买决策的文化因素",
    "features.report.title": "自动化报告",
    "features.report.desc": "基于访谈数据生成全面的商业洞察报告和可视化",
    
    // How It Works
    "howItWorks.title": "工作流程",
    "howItWorks.step1.title": "定义研究",
    "howItWorks.step1.desc": "设置研究目标、目标受众和关键问题",
    "howItWorks.step2.title": "生成画像",
    "howItWorks.step2.desc": "AI 创建符合您标准的多样化消费者画像",
    "howItWorks.step3.title": "进行访谈",
    "howItWorks.step3.desc": "与 AI 画像进行对话以收集洞察",
    "howItWorks.step4.title": "获取报告",
    "howItWorks.step4.desc": "接收详细的分析和可操作的建议",
    
    // Pricing
    "pricing.title": "选择您的方案",
    "pricing.subtitle": "从免费开始，随业务增长而扩展",
    "pricing.free.title": "免费",
    "pricing.free.price": "¥0",
    "pricing.free.period": "/月",
    "pricing.free.cta": "开始使用",
    "pricing.free.feature1": "100 万免费 Token",
    "pricing.free.feature2": "最多 3 个研究项目",
    "pricing.free.feature3": "每个研究 5 个画像",
    "pricing.free.feature4": "基础报告",
    "pricing.pro.title": "专业版",
    "pricing.pro.price": "¥299",
    "pricing.pro.period": "/月",
    "pricing.pro.cta": "升级到专业版",
    "pricing.pro.feature1": "每月 1000 万 Token",
    "pricing.pro.feature2": "无限研究项目",
    "pricing.pro.feature3": "每个研究 20 个画像",
    "pricing.pro.feature4": "高级分析",
    "pricing.pro.feature5": "优先支持",
    "pricing.max.title": "企业版",
    "pricing.max.price": "¥999",
    "pricing.max.period": "/月",
    "pricing.max.cta": "升级到企业版",
    "pricing.max.feature1": "无限 Token",
    "pricing.max.feature2": "无限一切",
    "pricing.max.feature3": "自定义画像数量",
    "pricing.max.feature4": "API 访问",
    "pricing.max.feature5": "专属客户经理",
    "pricing.max.feature6": "定制集成",
    
    // Dashboard
    "dashboard.title": "我的研究项目",
    "dashboard.createNew": "创建新研究",
    "dashboard.noStudies": "还没有研究项目",
    "dashboard.noStudiesDesc": "创建您的第一个 AI 驱动的消费者研究项目",
    "dashboard.status.draft": "草稿",
    "dashboard.status.generating": "生成中",
    "dashboard.status.interviewing": "访谈中",
    "dashboard.status.completed": "已完成",
    "dashboard.personas": "个画像",
    "dashboard.interviews": "次访谈",
    "dashboard.viewDetails": "查看详情",
    
    // New Study Form
    "newStudy.title": "创建新研究",
    "newStudy.step1": "研究目标",
    "newStudy.step2": "目标受众",
    "newStudy.step3": "研究问题",
    "newStudy.step4": "确认",
    "newStudy.studyTitle": "研究标题",
    "newStudy.studyTitlePlaceholder": "例如：千禧一代的购物习惯",
    "newStudy.description": "描述（可选）",
    "newStudy.descriptionPlaceholder": "简要描述您的研究目标...",
    "newStudy.objective": "研究目标",
    "newStudy.objectivePlaceholder": "您想通过这项研究了解什么？",
    "newStudy.targetAudience": "目标受众",
    "newStudy.targetAudiencePlaceholder": "描述您的目标受众...",
    "newStudy.next": "下一步",
    "newStudy.previous": "上一步",
    "newStudy.create": "创建研究",
    "newStudy.creating": "创建中...",
    
    // Study Detail
    "study.overview": "概览",
    "study.personas": "画像",
    "study.interviews": "访谈",
    "study.report": "报告",
    "study.generatePersonas": "生成画像",
    "study.generating": "生成中...",
    "study.startInterview": "开始访谈",
    "study.viewReport": "查看报告",
    "study.noPersonas": "还没有生成画像",
    "study.noPersonasDesc": "点击上方按钮生成 AI 人物画像",
    
    // Interview
    "interview.selectPersona": "选择画像",
    "interview.startInterview": "开始访谈",
    "interview.askQuestion": "提问...",
    "interview.send": "发送",
    "interview.backToStudy": "返回研究",
    
    // Report
    "report.title": "研究报告",
    "report.generate": "生成报告",
    "report.regenerate": "重新生成",
    "report.export": "导出",
    "report.executiveSummary": "执行摘要",
    "report.keyFindings": "关键发现",
    "report.audienceInsights": "受众洞察",
    "report.behavioralAnalysis": "行为分析",
    "report.recommendations": "建议",
    "report.noReport": "还没有生成报告",
    "report.noReportDesc": "基于您的 AI 画像访谈生成全面的研究报告",
    
    // Case Studies
    "caseStudies.title": "案例研究",
    "caseStudies.subtitle": "探索 AI 驱动的消费者研究的真实案例，发现推动商业决策的洞察。",
    "caseStudies.featured": "精选",
    "caseStudies.viewStudy": "查看研究",
    "caseStudies.noCases": "还没有案例研究",
    "caseStudies.noCasesDesc": "稍后查看鼓舞人心的 AI 驱动研究案例",
    
    // NewStudyInteractive
    "newStudyInteractive.welcome.title": "欢迎使用 AI 商业调研平台",
    "newStudyInteractive.welcome.subtitle": "我将帮助您设计一个系统化的商业调研方案。通过几个简单的问题，我们将明确您的研究目标、分析框架和执行计划。",
    "newStudyInteractive.welcome.features.title": "您将获得",
    "newStudyInteractive.welcome.features.item1": "基于 JTBD 框架的深度用户洞察",
    "newStudyInteractive.welcome.features.item2": "AI 驱动的多维度人物画像生成",
    "newStudyInteractive.welcome.features.item3": "结构化的商业机会分析报告",
    "newStudyInteractive.welcome.features.item4": "可操作的产品设计和市场策略建议",
    "newStudyInteractive.welcome.start": "开始设计研究方案",

    "newStudyInteractive.background.title": "研究背景",
    "newStudyInteractive.background.subtitle": "首先，让我了解一下您的研究对象和目标。",
    "newStudyInteractive.background.audienceLabel": "目标人群画像",
    "newStudyInteractive.background.audiencePlaceholder": "例如：40-65岁，本科以上学历，一、二线城市工作或居住的国央企中高层，注重效率，对新工具接受度高...",
    "newStudyInteractive.background.objectiveLabel": "调研目标",
    "newStudyInteractive.background.objectivePlaceholder": "例如：了解这些人对 AI 在效率提升、健康管理和情感陪伴上的需求和痛点；了解对于抗衰和康养方面的核心诉求...",
    "newStudyInteractive.background.industryAnalysis": "行业背景分析",
    "newStudyInteractive.background.quickAnalysis": "快速了解目标人群的行业背景和趋势",
    "newStudyInteractive.background.analyzing": "正在分析相关行业数据...",
    "newStudyInteractive.background.analysisResult": "基于您的目标受众分析，我们发现：",

    "newStudyInteractive.scenario.title": "研究场景",
    "newStudyInteractive.scenario.subtitle": "这个群体在考虑使用产品/服务时，您更关注他们在哪个决策场景？",
    "newStudyInteractive.scenario.generating": "正在生成针对您目标人群的场景描述...",
    "newStudyInteractive.scenario.work": "工作场景",
    "newStudyInteractive.scenario.workDefault": "如会议、报告、决策支持等高压时刻",
    "newStudyInteractive.scenario.personal": "个人/家庭场景",
    "newStudyInteractive.scenario.personalDefault": "如健康焦虑、养老规划、家人关怀等私密时刻",
    "newStudyInteractive.scenario.both": "两个场景都关注",
    "newStudyInteractive.scenario.bothDefault": "综合研究工作和个人场景下的决策逻辑",

    "newStudyInteractive.dimensions.title": "关注维度",
    "newStudyInteractive.dimensions.subtitle": "对于这个群体，您希望重点探索哪些方面？（可多选）",
    "newStudyInteractive.dimensions.recommending": "正在基于您的调研目标推荐相关维度...",

    "newStudyInteractive.confirm.title": "研究计划确认",
    "newStudyInteractive.confirm.subtitle": "请确认您的研究方案，我们将基于此生成 AI 人物画像并开始深度访谈。",
    "newStudyInteractive.confirm.intent": "📋 研究意图",
    "newStudyInteractive.confirm.targetAudience": "研究对象：",
    "newStudyInteractive.confirm.researchGoal": "研究目标：",
    "newStudyInteractive.confirm.scenario": "研究场景：",
    "newStudyInteractive.confirm.dimensions": "关注维度：",
    "newStudyInteractive.confirm.method": "🔬 研究方法",
    "newStudyInteractive.confirm.recommendingPlan": "正在基于您的调研维度推荐最佳调研计划...",
    "newStudyInteractive.confirm.aiPlan": "🤖 AI 推荐计划",
    "newStudyInteractive.confirm.interviewCount": "访谈数量：",
    "newStudyInteractive.confirm.duration": "访谈时长：",
    "newStudyInteractive.confirm.questionType": "问题类型：",
    "newStudyInteractive.confirm.rationale": "推荐理由：",
    "newStudyInteractive.confirm.analysisFrame": "分析框架：",
    "newStudyInteractive.confirm.analysisFrameDesc": "JTBD（Jobs To Be Done）——聚焦用户在特定情境下“雇佣”产品/服务的真实动机、障碍和期待",
    "newStudyInteractive.confirm.researchMode": "研究方式：",
    "newStudyInteractive.confirm.researchModeDesc": "一对一深度访谈（interview）——深入探索个人经历、决策过程和深层动机",
    "newStudyInteractive.confirm.personaConfig": "人设配置：",
    "newStudyInteractive.confirm.output": "📊 预期产出",
    "newStudyInteractive.confirm.output1": "需求痛点地图：真实需求、痛点强度、未被满足的需求",
    "newStudyInteractive.confirm.output2": "JTBD 任务拆解：关键任务及背后的功能性、情感性、社交性动机",
    "newStudyInteractive.confirm.output3": "消费决策模型：决策路径、关键影响因素、价格敏感区间",
    "newStudyInteractive.confirm.output4": "商业机会识别：产品/服务设计建议、市场切入策略",
    "newStudyInteractive.confirm.personaCount": "人设数量",
    "newStudyInteractive.confirm.personaCountRange": "数量范围：3-10 个",
    "newStudyInteractive.confirm.start": "开始执行研究",
    
    "newStudyInteractive.creating.title": "正在创建您的研究项目...",
    "newStudyInteractive.creating.subtitle": "我们正在生成 AI 人物画像并准备深度访谈，请稍候",
    
    "common.next": "下一步",
    "common.prev": "上一步",
    "common.times": "次",
    "common.minutes": "分钟/次",
    
    // AutoInterview
    "autoInterview.title": "自动化调研",
    "autoInterview.subtitle": "AI 智能体将自动对所有受访者进行深度访谈",
    "autoInterview.start": "开始访谈",
    "autoInterview.progress": "调研进度",
    "autoInterview.completed": "位受访者已完成",
    "autoInterview.currentInterview": "当前访谈",
    "autoInterview.round": "第 {round} 轮",
    "autoInterview.question": "问题",
    "autoInterview.answer": "回答",
    "autoInterview.jtbdInsight": "JTBD 洞察",
    "autoInterview.nextQuestion": "下一个问题思考",
    "autoInterview.allCompleted": "所有访谈已完成！",
    "autoInterview.viewReport": "查看报告",
    "autoInterview.backToStudy": "返回调研详情",
    
    // PersonaCard
    "personaCard.years": "岁",
    "personaCard.traits": "性格特征",
    "personaCard.values": "核心价值观",
    "personaCard.motivations": "动机驱动",
    "personaCard.painPoints": "痛点",
    "personaCard.behaviorPatterns": "行为模式",
    "personaCard.shoppingHabits": "购物习惯：",
    "personaCard.mediaConsumption": "媒体消费：",
    "personaCard.decisionFactors": "决策因素：",
    "personaCard.viewDetails": "查看详情",
    "personaCard.hideDetails": "收起详情",
    "personaCard.startInterview": "开始访谈",
    
    // Deep Report
    "deepInsightReport": "深度洞察报告",
    "reportDate": "报告日期",
    "interviewees": "受访者",
    "interviews": "访谈次数",
    "researchInstitutionTagline": "人类学田野调研 · 商业洞察咨询",
    "deepReport.subtitle": "深度商业洞察报告",
    "deepReport.background": "研究背景",
    "deepReport.objectives": "研究目标",
    "deepReport.methodology": "研究方法",
    "deepReport.jobStories": "Job Stories",
    "deepReport.needs": "核心需求",
    "deepReport.barriers": "主要障碍",
    "deepReport.trustFactors": "信任因素",
    "deepReport.importance": "重要性",
    "deepReport.urgency": "紧迫性",
    "deepReport.decisionProcess": "决策过程",
    "deepReport.opportunities": "商业机会",
    "deepReport.impact": "预期影响",
    "deepReport.recommendations": "行动建议",
    "deepReport.footer": "本报告由 AI 商业调研平台自动生成",
    "deepReport.sources.title": "引用来源",
    "deepReport.sources.yearsOld": "岁",
    "deepReport.sources.interviewDate": "访谈日期",
    
    // Footer
    "footer.product": "产品",
    "footer.features": "功能",
    "footer.pricing": "定价",
    "footer.caseStudies": "案例研究",
    "footer.company": "公司",
    "footer.about": "关于我们",
    "footer.contact": "联系我们",
    "footer.resources": "资源",
    "footer.docs": "文档",
    "footer.support": "支持",
    "footer.rights": "版权所有",
  },
  en: {
    // Navigation
    "nav.products": "Products",
    "nav.productsDesc": "Create AI-powered research studies",
    "nav.home": "Home",
    "nav.caseStudies": "Case Studies",
    "nav.pricing": "Pricing",
    "nav.dashboard": "Dashboard",
    "nav.signIn": "Sign In",
    "nav.signOut": "Sign Out",
    "nav.myStudies": "My Studies",
    
    // Home Page
    "home.hero.title": "The AI Research Agent",
    "home.hero.subtitle": "Simulating Consumers",
    "home.hero.description": "Automatically build personas, conduct interviews, and analyze patterns to reveal the emotional and cognitive factors behind human choices.",
    "home.hero.cta": "Start Your Study",
    "home.stats.personas": "AI Personas Created",
    "home.stats.interviews": "Interviews Conducted",
    "home.stats.minutes": "Minutes per Research",
    "home.stats.title": "AI PERSONA RESEARCH AT SCALE",
    "home.stats.subtitle": "Building Real Person Agents to understand",
    "home.stats.highlight": "human decisions",

    "home.features.sectionTitle": "RESEARCH APPLICATIONS",
    "home.features.mainTitle": "AI Persona Research in Action",
    "home.features.description": "See how AI Personas built from in-depth interviews transform research across different scenarios.",
    "home.features.testing.title": "Testing",
    "home.features.testing.desc": "Interview AI Personas to test marketing messages, product concepts, and campaign ideas with authentic reactions.",
    "home.features.planning.title": "Planning",
    "home.features.planning.desc": "Create strategic frameworks by interviewing AI Personas about preferences and priorities to inform roadmaps.",
    "home.features.insights.title": "Insights",
    "home.features.insights.desc": "Uncover behavioral patterns and motivations through interviews with AI Personas representing target audiences.",
    "home.features.creation.title": "Creation",
    "home.features.creation.desc": "Brainstorm and co-create with AI Personas to generate innovative ideas and validate creative concepts.",

    "home.workflow.sectionTitle": "SUBJECTIVE WORLD MODELING IN ACTION",
    "home.workflow.mainTitle": "From question to insights in minutes",
    "home.workflow.step1.title": "Persona Generation",
    "home.workflow.step1.desc": "Generate diverse AI personas based on real behavioral patterns and demographic insights.",
    "home.workflow.step2.title": "AI-Led Interviews",
    "home.workflow.step2.desc": "Conduct natural conversations with AI personas to uncover deep motivations and key decision drivers.",
    "home.workflow.step3.title": "Behavior Analysis",
    "home.workflow.step3.desc": "Identify emotional triggers, cognitive biases, and cultural factors that influence purchasing decisions.",
    "home.workflow.step4.title": "Instant Insights",
    "home.workflow.step4.desc": "Generate comprehensive insights in minutes instead of traditional weeks-long research processes.",

    "home.tech.sectionTitle": "CORE TECHNOLOGY",
    "home.tech.mainTitle": "AI Personas from Deep Interviews",
    "home.tech.description": "Advanced AI Personas that simulate authentic human cognition. Whether using our extensive library or creating private personas from your own interview data, these agents maintain consistent personalities and behavioral frameworks.",
    "home.tech.accuracy": "Simulation Accuracy",
    "home.tech.accuracyDesc": "Human-like behavioral consistency in AI persona responses",
    "home.tech.socialBased": "Social Media Based",
    "home.tech.interviewBased": "Deep Interview Based",
    "home.tech.proprietary": "Proprietary",
    "home.tech.badge1": "Consistent personality across conversations",
    "home.tech.badge2": "Authentic emotional responses and biases",
    "home.tech.badge3": "Realistic decision-making patterns",
    "home.testimonial.quote": "Our deep interview AI Personas are a form of high-precision consumer simulation technology. You can also apply this same powerful technology to your own interview transcripts.",

    "home.tech.ecosystemTitle": "AGENT ECOSYSTEM",
    "home.tech.ecosystemMainTitle": "Agent Ecosystem",
    "home.tech.card1.title": "AI Simulated Persona (Social Media)",
    "home.tech.card1.desc": "Based on social media data analysis",
    "home.tech.card2.title": "AI Sample Persona (Deep Interview)",
    "home.tech.card2.desc": "Based on in-depth interview data",
    "home.tech.card3.title": "AI Twin Persona (Private)",
    "home.tech.card3.desc": "Built from your own private interview data",

    "home.cta.title": "Build Your Custom AI Research Panel",
    "home.cta.description": "Create private, high-fidelity AI Personas from your own interview data, or leverage our extensive library to discover deep consumer insights.",
    "home.cta.viewCases": "View Case Studies",
    
    // Hero Section
    "hero.title": "The AI Research Agent",
    "hero.subtitle": "Simulating Consumers",
    "hero.description": "Automatically build personas, conduct interviews, and analyze patterns to reveal the emotional and cognitive factors behind human choices.",
    "hero.cta": "Start Your Study",
    "hero.trusted": "Trusted by leading organizations",
    
    // Features
    "features.title": "AI-Powered Consumer Research",
    "features.personaGen.title": "AI Persona Generation",
    "features.personaGen.desc": "Automatically create diverse consumer personas based on demographic and behavioral criteria",
    "features.interview.title": "Simulated Interviews",
    "features.interview.desc": "Conduct natural conversations with AI personas to gather deep insights and decision drivers",
    "features.analysis.title": "Behavioral Analysis",
    "features.analysis.desc": "Identify emotional triggers, cognitive biases, and cultural factors that influence purchase decisions",
    "features.report.title": "Automated Reports",
    "features.report.desc": "Generate comprehensive business insights reports and visualizations based on interview data",
    
    // How It Works
    "howItWorks.title": "How It Works",
    "howItWorks.step1.title": "Define Research",
    "howItWorks.step1.desc": "Set your research objectives, target audience, and key questions",
    "howItWorks.step2.title": "Generate Personas",
    "howItWorks.step2.desc": "AI creates diverse consumer personas matching your criteria",
    "howItWorks.step3.title": "Conduct Interviews",
    "howItWorks.step3.desc": "Have conversations with AI personas to gather insights",
    "howItWorks.step4.title": "Get Reports",
    "howItWorks.step4.desc": "Receive detailed analysis and actionable recommendations",
    
    // Pricing
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Start free and scale as you grow",
    "pricing.free.title": "Free",
    "pricing.free.price": "$0",
    "pricing.free.period": "/month",
    "pricing.free.cta": "Get Started",
    "pricing.free.feature1": "1M free tokens",
    "pricing.free.feature2": "Up to 3 studies",
    "pricing.free.feature3": "5 personas per study",
    "pricing.free.feature4": "Basic reports",
    "pricing.pro.title": "Pro",
    "pricing.pro.price": "$49",
    "pricing.pro.period": "/month",
    "pricing.pro.cta": "Upgrade to Pro",
    "pricing.pro.feature1": "10M tokens/month",
    "pricing.pro.feature2": "Unlimited studies",
    "pricing.pro.feature3": "20 personas per study",
    "pricing.pro.feature4": "Advanced analytics",
    "pricing.pro.feature5": "Priority support",
    "pricing.max.title": "Max",
    "pricing.max.price": "$149",
    "pricing.max.period": "/month",
    "pricing.max.cta": "Upgrade to Max",
    "pricing.max.feature1": "Unlimited tokens",
    "pricing.max.feature2": "Unlimited everything",
    "pricing.max.feature3": "Custom persona count",
    "pricing.max.feature4": "API access",
    "pricing.max.feature5": "Dedicated account manager",
    "pricing.max.feature6": "Custom integrations",
    
    // Dashboard
    "dashboard.title": "My Research Projects",
    "dashboard.createNew": "Create New Study",
    "dashboard.noStudies": "No studies yet",
    "dashboard.noStudiesDesc": "Create your first AI-powered consumer research project",
    "dashboard.status.draft": "Draft",
    "dashboard.status.generating": "Generating",
    "dashboard.status.interviewing": "Interviewing",
    "dashboard.status.completed": "Completed",
    "dashboard.personas": "personas",
    "dashboard.interviews": "interviews",
    "dashboard.viewDetails": "View Details",
    
    // New Study Form
    "newStudy.title": "Create New Study",
    "newStudy.step1": "Research Objective",
    "newStudy.step2": "Target Audience",
    "newStudy.step3": "Research Questions",
    "newStudy.step4": "Confirm",
    "newStudy.studyTitle": "Study Title",
    "newStudy.studyTitlePlaceholder": "e.g., Millennial Shopping Habits",
    "newStudy.description": "Description (Optional)",
    "newStudy.descriptionPlaceholder": "Briefly describe your research goals...",
    "newStudy.objective": "Research Objective",
    "newStudy.objectivePlaceholder": "What do you want to learn from this study?",
    "newStudy.targetAudience": "Target Audience",
    "newStudy.targetAudiencePlaceholder": "Describe your target audience...",
    "newStudy.next": "Next",
    "newStudy.previous": "Previous",
    "newStudy.create": "Create Study",
    "newStudy.creating": "Creating...",
    
    // Study Detail
    "study.overview": "Overview",
    "study.personas": "Personas",
    "study.interviews": "Interviews",
    "study.report": "Report",
    "study.generatePersonas": "Generate Personas",
    "study.generating": "Generating...",
    "study.startInterview": "Start Interview",
    "study.viewReport": "View Report",
    "study.noPersonas": "No personas generated yet",
    "study.noPersonasDesc": "Click the button above to generate AI personas",
    
    // Interview
    "interview.selectPersona": "Select Persona",
    "interview.startInterview": "Start Interview",
    "interview.askQuestion": "Ask a question...",
    "interview.send": "Send",
    "interview.backToStudy": "Back to Study",
    
    // Report
    "report.title": "Research Report",
    "report.generate": "Generate Report",
    "report.regenerate": "Regenerate",
    "report.export": "Export",
    "report.executiveSummary": "Executive Summary",
    "report.keyFindings": "Key Findings",
    "report.audienceInsights": "Audience Insights",
    "report.behavioralAnalysis": "Behavioral Analysis",
    "report.recommendations": "Recommendations",
    "report.noReport": "No report generated yet",
    "report.noReportDesc": "Generate a comprehensive research report based on your AI persona interviews",
    
    // Case Studies
    "caseStudies.title": "Case Studies",
    "caseStudies.subtitle": "Explore real-world examples of AI-powered consumer research and discover the insights that drive business decisions.",
    "caseStudies.featured": "Featured",
    "caseStudies.viewStudy": "View Study",
    "caseStudies.noCases": "No case studies yet",
    "caseStudies.noCasesDesc": "Check back soon for inspiring examples of AI-powered research",
    
    // NewStudyInteractive
    "newStudyInteractive.welcome.title": "Welcome to AI Business Research Platform",
    "newStudyInteractive.welcome.subtitle": "I will help you design a systematic business research plan. Through a few simple questions, we will clarify your research objectives, analytical framework, and execution plan.",
    "newStudyInteractive.welcome.features.title": "You will get",
    "newStudyInteractive.welcome.features.item1": "Deep user insights based on the JTBD framework",
    "newStudyInteractive.welcome.features.item2": "AI-driven multi-dimensional persona generation",
    "newStudyInteractive.welcome.features.item3": "Structured business opportunity analysis report",
    "newStudyInteractive.welcome.features.item4": "Actionable product design and market strategy recommendations",
    "newStudyInteractive.welcome.start": "Start Designing Research Plan",

    "newStudyInteractive.background.title": "Research Background",
    "newStudyInteractive.background.subtitle": "First, let me understand your research subjects and objectives.",
    "newStudyInteractive.background.audienceLabel": "Target Audience Profile",
    "newStudyInteractive.background.audiencePlaceholder": "e.g., 40-65 years old, bachelor's degree or above, middle to senior management in state-owned enterprises in tier 1-2 cities, efficiency-oriented, high acceptance of new tools...",
    "newStudyInteractive.background.objectiveLabel": "Research Objective",
    "newStudyInteractive.background.objectivePlaceholder": "e.g., Understand their needs and pain points regarding AI in efficiency improvement, health management, and emotional companionship; understand their core demands for anti-aging and wellness...",
    "newStudyInteractive.background.industryAnalysis": "Industry Background Analysis",
    "newStudyInteractive.background.quickAnalysis": "Quickly understand industry background and trends",
    "newStudyInteractive.background.analyzing": "Analyzing relevant industry data...",
    "newStudyInteractive.background.analysisResult": "Based on your target audience analysis, we found:",

    "newStudyInteractive.scenario.title": "Research Scenario",
    "newStudyInteractive.scenario.subtitle": "In which decision-making scenario do you focus on when this group considers using products/services?",
    "newStudyInteractive.scenario.generating": "Generating scenario descriptions for your target audience...",
    "newStudyInteractive.scenario.work": "Work Scenario",
    "newStudyInteractive.scenario.workDefault": "High-pressure moments like meetings, reports, decision support",
    "newStudyInteractive.scenario.personal": "Personal/Family Scenario",
    "newStudyInteractive.scenario.personalDefault": "Private moments like health anxiety, retirement planning, family care",
    "newStudyInteractive.scenario.both": "Both Scenarios",
    "newStudyInteractive.scenario.bothDefault": "Comprehensive study of decision logic in work and personal contexts",

    "newStudyInteractive.dimensions.title": "Focus Dimensions",
    "newStudyInteractive.dimensions.subtitle": "What aspects do you want to explore deeply for this group? (Multiple selection allowed)",
    "newStudyInteractive.dimensions.recommending": "Recommending relevant dimensions based on your research goals...",

    "newStudyInteractive.confirm.title": "Confirm Research Plan",
    "newStudyInteractive.confirm.subtitle": "Please confirm your research plan. We will generate AI personas and start in-depth interviews based on this.",
    "newStudyInteractive.confirm.intent": "📋 Research Intent",
    "newStudyInteractive.confirm.targetAudience": "Target Audience:",
    "newStudyInteractive.confirm.researchGoal": "Research Goal:",
    "newStudyInteractive.confirm.scenario": "Research Scenario:",
    "newStudyInteractive.confirm.dimensions": "Focus Dimensions:",
    "newStudyInteractive.confirm.method": "🔬 Research Methodology",
    "newStudyInteractive.confirm.recommendingPlan": "Recommending best research plan based on your dimensions...",
    "newStudyInteractive.confirm.aiPlan": "🤖 AI Recommended Plan",
    "newStudyInteractive.confirm.interviewCount": "Interviews:",
    "newStudyInteractive.confirm.duration": "Duration:",
    "newStudyInteractive.confirm.questionType": "Question Type:",
    "newStudyInteractive.confirm.rationale": "Rationale:",
    "newStudyInteractive.confirm.analysisFrame": "Analysis Framework:",
    "newStudyInteractive.confirm.analysisFrameDesc": "JTBD (Jobs To Be Done) — Focus on real motivations, barriers, and expectations when users 'hire' products/services",
    "newStudyInteractive.confirm.researchMode": "Research Mode:",
    "newStudyInteractive.confirm.researchModeDesc": "One-on-one in-depth interview — Explore personal experiences, decision processes, and deep motivations",
    "newStudyInteractive.confirm.personaConfig": "Persona Config:",
    "newStudyInteractive.confirm.output": "📊 Expected Output",
    "newStudyInteractive.confirm.output1": "Needs & Pain Points Map: Real needs, pain intensity, unmet needs",
    "newStudyInteractive.confirm.output2": "JTBD Task Breakdown: Key tasks and underlying functional, emotional, social motivations",
    "newStudyInteractive.confirm.output3": "Consumption Decision Model: Decision path, key influencing factors, price sensitivity",
    "newStudyInteractive.confirm.output4": "Business Opportunity Identification: Product/service design suggestions, market entry strategies",
    "newStudyInteractive.confirm.personaCount": "Persona Count",
    "newStudyInteractive.confirm.personaCountRange": "Range: 3-10 personas",
    "newStudyInteractive.confirm.start": "Execute Research",
    
    "newStudyInteractive.creating.title": "Creating Your Research Project...",
    "newStudyInteractive.creating.subtitle": "We are generating AI personas and preparing for in-depth interviews, please wait",
    
    "common.next": "Next",
    "common.prev": "Previous",
    "common.times": "times",
    "common.minutes": "min/session",
    
    // AutoInterview
    "autoInterview.title": "Automated Research",
    "autoInterview.subtitle": "AI agent will automatically conduct in-depth interviews with all respondents",
    "autoInterview.start": "Start Interview",
    "autoInterview.progress": "Research Progress",
    "autoInterview.completed": "respondents completed",
    "autoInterview.currentInterview": "Current Interview",
    "autoInterview.round": "Round {round}",
    "autoInterview.question": "Question",
    "autoInterview.answer": "Answer",
    "autoInterview.jtbdInsight": "JTBD Insight",
    "autoInterview.nextQuestion": "Next Question Thinking",
    "autoInterview.allCompleted": "All interviews completed!",
    "autoInterview.viewReport": "View Report",
    "autoInterview.backToStudy": "Back to Study Details",
    
    // PersonaCard
    "personaCard.years": "years old",
    "personaCard.traits": "Personality Traits",
    "personaCard.values": "Core Values",
    "personaCard.motivations": "Motivations",
    "personaCard.painPoints": "Pain Points",
    "personaCard.behaviorPatterns": "Behavior Patterns",
    "personaCard.shoppingHabits": "Shopping Habits:",
    "personaCard.mediaConsumption": "Media Consumption:",
    "personaCard.decisionFactors": "Decision Factors:",
    "personaCard.viewDetails": "View Details",
    "personaCard.hideDetails": "Hide Details",
    "personaCard.startInterview": "Start Interview",
    
    // Deep Report
    "deepInsightReport": "Deep Insight Report",
    "reportDate": "Report Date",
    "interviewees": "Interviewees",
    "interviews": "Interviews",
    "researchInstitutionTagline": "Anthropological Field Research · Business Insight Consulting",
    "deepReport.subtitle": "In-Depth Business Insights Report",
    "deepReport.background": "Research Background",
    "deepReport.objectives": "Research Objectives",
    "deepReport.methodology": "Methodology",
    "deepReport.jobStories": "Job Stories",
    "deepReport.needs": "Core Needs",
    "deepReport.barriers": "Key Barriers",
    "deepReport.trustFactors": "Trust Factors",
    "deepReport.importance": "Importance",
    "deepReport.urgency": "Urgency",
    "deepReport.decisionProcess": "Decision Process",
    "deepReport.opportunities": "Business Opportunities",
    "deepReport.impact": "Expected Impact",
    "deepReport.recommendations": "Action Recommendations",
    "deepReport.footer": "This report was automatically generated by AI Business Research Platform",
    "deepReport.sources.title": "Citation Sources",
    "deepReport.sources.yearsOld": " years old",
    "deepReport.sources.interviewDate": "Interview Date",
    
    // Footer
    "footer.product": "Products",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.caseStudies": "Case Studies",
    "footer.company": "Company",
    "footer.about": "About",
    "footer.contact": "Contact",
    "footer.resources": "Resources",
    "footer.docs": "Documentation",
    "footer.support": "Support",
    "footer.rights": "All rights reserved",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "zh";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.zh] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
